###

POST http://localhost:8080/media/bytes
Content-Type: image/jpeg

< qa.jpg

###

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="js.jpg"
Content-Type: image/jpeg

< js.jpg
--WebBoundary--

###

POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="JavaDev.jpg"
Content-Type: image/jpeg

< JavaDev.jpg
--WebBoundary
Content-Disposition: form-data; name="files"; filename="Phyton.jpg"
Content-Type: image/jpeg

< Phyton.jpg
--WebBoundary--

###

GET http://localhost:8080/courses/getAll

###

GET http://localhost:8080/courses/getById?id=3

###

POST http://localhost:8080/courses/save
Content-Type: application/json

{
  "id": 0,
  "courseId": 6,
  "name": "Java",
  "price":25000,
  "numberseats": 6
}

###

POST http://localhost:8080/courses/removeById?id=6

###

GET http://localhost:8080/registrations/getAll

###

GET http://localhost:8080/registrations/getById?id=8

###

POST http://localhost:8080/registrations/save
Content-Type: application/json

{
  "id": 0,
  "name": "Java",
  "price": 25000,
  "customerName":"Alan"
}

###

GET http://localhost:8080/registrations/getParticipants?courseId=0

