###

POST http://localhost:8080/media/bytes
Content-Type: image/jpeg

< qa.jpg

###

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="js.jpg"
Content-Type: image/jpeg

< js.jpg
--WebBoundary--

###

POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="JavaDev.jpg"
Content-Type: image/jpeg

< JavaDev.jpg
--WebBoundary
Content-Disposition: form-data; name="files"; filename="Phyton.jpg"
Content-Type: image/jpeg

< Phyton.jpg
--WebBoundary--

###

GET http://localhost:8080/courses/getAll

###

GET http://localhost:8080/courses/getById?id=6

